# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'voxTest2' do
  use_frameworks!
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for voxTest
  pod "React", :path => "../node_modules/react-native", :subspecs => [
    'Core',
    'CxxBridge',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'DevSupport',
    'RCTAnimation',
    'RCTLinkingIOS'
    # Add any other subspecs you want to use in your project
  ]

    pod "react-native-voximplant", path: "../node_modules/react-native-voximplant"
    pod "yoga", path: "../node_modules/react-native/ReactCommon/yoga"

    # Third party deps podspec link
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end

 